# Generated by Django 6.0.1 on 2026-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediScanApp', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='profile.jpg', null=True, upload_to=''),
        ),
    ]
