# Generated by Django 6.0.1 on 2026-01-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediScanApp', '0005_user_avater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='img/profile.jpg', null=True, upload_to=''),
        ),
    ]
